#!/bin/bash
# https://raw.githubusercontent.com/hankpillow/wtchr/master/wtchr

help='printf "# usage:\n# ./wtchr src \"echo changed\"\n"'
if [[ ! -d $1 ]];
then
  printf "#! missing target to watch\n"
  eval $help
  exit 1
fi

if [[ ! -n $2 ]];
then
  printf "#! missing trigger to call\n"
  eval $help
  exit 1
fi

args=""
if [[ -n $3 ]];
then
	args="$3"
fi

target="$1"
trigger="$2"

finder="find $target -type f $args | xargs ls -o | grep $target"
old=$(eval "$finder")

clear
echo "# watching: $target $args"
printf "\n$old" | sed -e 's/^[ \t]*//'

while :
do
  new=$(eval "$finder")
  changes=$(diff -q <(printf "\n$old") <(printf "\n$new"))
  if [[ $? != 0 ]];
  then
    printf "\n#> changed!\n"
    old=$new
    eval "$trigger"
    if [[ $? != 0 ]];
    then
      echo "# stop watching due to trigger exit code: $?"
      exit 1
    fi
  fi
  sleep 1
  clear
  echo "# watching: $target $args"
  printf "\n$old" | sed -e 's/^[ \t]*//'
done
